# -*- coding: utf-8 -*-
"""
Created on Tue May 11 21:21:18 2021

@author: myhom
"""

import streamlit as st
import streamlit.components.v1 as components


def write():
    
    st.header("The Rent in Austin")
    st.subheader("**Introduction**")
    ##income1,immi1=st.beta_columns(2)
    st.markdown("Economy Part")
    income ="""https://datausa.io/profile/geo/austin-tx/economy/income?viz=true"""
    components.iframe(income,width=1000,height=500,scrolling=True)
    em = "https://datausa.io/profile/geo/austin-tx/covid/covid-employment?viz=true"
    components.iframe(em,width=1000,height=500,scrolling=True)
    ##income1 = components.iframe(income,width=1000,height=500,scrolling=True)
    immi = """https://datausa.io/profile/geo/austin-tx/demographics/foreign_born?viz=true"""
    components.iframe(immi,width=1000,height=500,scrolling=True)
    ##immi1 = components.iframe(immi,width=1000,height=500,scrolling=True)
    cz = "https://datausa.io/profile/geo/austin-tx/demographics/citizenship?viz=true"
    components.iframe(cz,width=1000,height=500,scrolling=True)
    propertyvalue = """https://datausa.io/profile/geo/austin-tx/housing/property_value?viz=true"""
    components.iframe(propertyvalue,width=1000,height=500,scrolling=True)
    pv="https://datausa.io/profile/geo/austin-tx/housing/household_income?viz=true" 
    components.iframe(pv,1000,700,True)
    rentvsown = "https://datausa.io/profile/geo/austin-tx/housing/rent_own?viz=true"
    components.iframe(rentvsown,width=1000,height=500,scrolling=True)
    html1="<div class='tableauPlaceholder' id='viz1620859341142' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Ai&#47;AirbnbAustinRegions&#47;GroupBookingStory&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='AirbnbAustinRegions&#47;GroupBookingStory' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Ai&#47;AirbnbAustinRegions&#47;GroupBookingStory&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='zh-Hans' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1620859341142');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='800px';vizElement.style.height='850px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>"
    components.html(html1,1000,500,True)
    html_temp = "<div class='tableauPlaceholder' id='viz1620764157103' style='position: relative'><noscript><a href='#'><img alt='Most Popular Neighborhoods in Austin ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;mo&#47;mostpopularhoodsinaustin_0&#47;Map&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='mostpopularhoodsinaustin_0&#47;Map' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;mo&#47;mostpopularhoodsinaustin_0&#47;Map&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='zh-Hans' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1620764157103');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>"
    components.html(html_temp,1000,500,scrolling=True)
    temp2 = """<div class='tableauPlaceholder' id='viz1620764267668' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Au&#47;Austin-HomeMarketAnalysis&#47;City&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='Austin-HomeMarketAnalysis&#47;City' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Au&#47;Austin-HomeMarketAnalysis&#47;City&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='zh-Hans' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1620764267668');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='1055px';vizElement.style.height='642px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>"""
    components.html(temp2,width=1000,height=500,scrolling=True)
    temp3="<div class='tableauPlaceholder' id='viz1620859103300' style='position: relative'><noscript><a href='#'><img alt='What does the Airbnb business in Austin look like? ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Au&#47;Austin_Airbnb_16118640907970&#47;AustinAirbnb&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='Austin_Airbnb_16118640907970&#47;AustinAirbnb' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Au&#47;Austin_Airbnb_16118640907970&#47;AustinAirbnb&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='zh-Hans' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1620859103300');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='1016px';vizElement.style.height='991px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>"
    components.html(temp3,width=1000,height=500,scrolling=True)
    temp4="<div class='tableauPlaceholder' id='viz1620859189007' style='position: relative'><noscript><a href='http:&#47;&#47;www.TexasNationalTitle.com'><img alt='Median Sales Price Appreciation by Zip CodeMarch 2020 to March 2021 ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Me&#47;MedianSalesPriceAppreciationbyZipCodeMarch2021&#47;Mar2021&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='MedianSalesPriceAppreciationbyZipCodeMarch2021&#47;Mar2021' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Me&#47;MedianSalesPriceAppreciationbyZipCodeMarch2021&#47;Mar2021&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='zh-Hans' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1620859189007');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.minWidth='420px';vizElement.style.maxWidth='650px';vizElement.style.width='100%';vizElement.style.minHeight='587px';vizElement.style.maxHeight='887px';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.minWidth='420px';vizElement.style.maxWidth='650px';vizElement.style.width='100%';vizElement.style.minHeight='587px';vizElement.style.maxHeight='887px';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';} else { vizElement.style.width='100%';vizElement.style.height='777px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>"
    components.html(temp4,width=1000,height=500,scrolling=True)
    temp8="<div class='tableauPlaceholder' id='viz1620859490626' style='position: relative'><noscript><a href='#'><img alt='Reviews Per Month ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Au&#47;AustinAirbnb_15643508724270&#47;ReviewsPerMonth&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='AustinAirbnb_15643508724270&#47;ReviewsPerMonth' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Au&#47;AustinAirbnb_15643508724270&#47;ReviewsPerMonth&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='zh-Hans' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1620859490626');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>"
    components.html(temp8,width=1000,height=500,scrolling=True)
    temp9="<div class='tableauPlaceholder' id='viz1620859557078' style='position: relative'><noscript><a href='#'><img alt='map_final ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;au&#47;austin_neighborhood_rents&#47;map_final&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='austin_neighborhood_rents&#47;map_final' /><param name='tabs' value='no' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;au&#47;austin_neighborhood_rents&#47;map_final&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='zh-Hans' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1620859557078');                    var vizElement = divElement.getElementsByTagName('object')[0];                    if ( divElement.offsetWidth > 800 ) { vizElement.style.width='754px';vizElement.style.height='827px';} else if ( divElement.offsetWidth > 500 ) { vizElement.style.width='754px';vizElement.style.height='827px';} else { vizElement.style.width='100%';vizElement.style.height='927px';}                     var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>"
    components.html(temp9,width=1000,height=500,scrolling=True)
    temp7="<div class='tableauPlaceholder' id='viz1620859423599' style='position: relative'><noscript><a href='#'><img alt=' ' src='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Au&#47;Austin-Analysis&#47;Rentv_HomeValues&#47;1_rss.png' style='border: none' /></a></noscript><object class='tableauViz'  style='display:none;'><param name='host_url' value='https%3A%2F%2Fpublic.tableau.com%2F' /> <param name='embed_code_version' value='3' /> <param name='site_root' value='' /><param name='name' value='Austin-Analysis&#47;Rentv_HomeValues' /><param name='tabs' value='yes' /><param name='toolbar' value='yes' /><param name='static_image' value='https:&#47;&#47;public.tableau.com&#47;static&#47;images&#47;Au&#47;Austin-Analysis&#47;Rentv_HomeValues&#47;1.png' /> <param name='animate_transition' value='yes' /><param name='display_static_image' value='yes' /><param name='display_spinner' value='yes' /><param name='display_overlay' value='yes' /><param name='display_count' value='yes' /><param name='language' value='zh-Hans' /></object></div>                <script type='text/javascript'>                    var divElement = document.getElementById('viz1620859423599');                    var vizElement = divElement.getElementsByTagName('object')[0];                    vizElement.style.width='100%';vizElement.style.height=(divElement.offsetWidth*0.75)+'px';                    var scriptElement = document.createElement('script');                    scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    vizElement.parentNode.insertBefore(scriptElement, vizElement);                </script>"
    components.html(temp7,width=1000,height=500,scrolling=True)
    
    